### ISSUE TITLE
This cache store does not support tagging

### ISSUE THREAD

**Issue by abada** [zenapply/laravel-shortener#3]
Nice work :)

But when i tried your package this error shown !

`This cache store does not support tagging`

But when change `config/cache.php` to `'default' => "array"` it works !

**Comment by tylercd100** [comment]
Hey @abada what was the default set to before?

To disable the caching feature you can change 

``` php
'cache' => [
        'enabled' => false
]
```

 in `config/shortener.php`

**Comment by abada** [comment]
Hi @tylercd100 No i want to keep `cache`  :)

**Comment by tylercd100** [comment]
k, What cache driver are you having the issue with?

**Comment by abada** [comment]
`file`

**Comment by tylercd100** [comment]
Hey @abada, please give version 5.0.1 a try. It should fix the issue :-)

**Comment by abada** [comment]
i will :)

**Comment by abada** [comment]
Thank you it works now 👍
